### ISSUE TITLE
Plugin prevents jQAssistant from starting

### ISSUE THREAD

**Issue by fxj9a** [softvis-research/jqa-githubissues-plugin#6]
Unfortunately this plugin doesn't work at all at this time.
Here's the output you will get with ```./bin/jqassistant.sh scan -f githubissues.xml```:

`2020-02-04 20:03:42.410 [main] INFO PluginConfigurationReaderImpl - Loaded jQAssistant plugins [CDI, Common, Core Analysis, Core Report, EJB3, GitHub-Issues, GraphML, JAX-RS, JPA 2, JSON, JUnit, Java, Java 8, Java EE 6, Maven 2 Repository, Maven 3, OSGi, RDBMS, Spring, TestNG, Tycho, XML, YAML].
2020-02-04 20:03:42.817 [main] INFO StoreFactory - Connecting to store at 'file:/home/adrian/Downloads/jqassistant-commandline-neo4jv3-1.7.0/jqassistant/store'
Exception in thread "main" com.buschmais.xo.api.XOException: com.buschmais.xo.neo4j.embedded.api.EmbeddedNeo4jXOProvider specified as XO provider must implement com.buschmais.xo.spi.bootstrap.XODatastoreProvider
	at com.buschmais.xo.impl.XOManagerFactoryImpl.<init>(XOManagerFactoryImpl.java:46)
	at com.buschmais.xo.impl.bootstrap.XOBootstrapServiceImpl.createXOManagerFactory(XOBootstrapServiceImpl.java:39)
	at com.buschmais.xo.api.bootstrap.XO.createXOManagerFactory(XO.java:49)
	at com.buschmais.jqassistant.core.store.impl.AbstractGraphStore.start(AbstractGraphStore.java:50)
	at com.buschmais.jqassistant.commandline.task.AbstractStoreTask.run(AbstractStoreTask.java:55)
	at com.buschmais.jqassistant.commandline.Main.executeTask(Main.java:259)
	at com.buschmais.jqassistant.commandline.Main.executeTasks(Main.java:208)
	at com.buschmais.jqassistant.commandline.Main.interpretCommandLine(Main.java:197)
	at com.buschmais.jqassistant.commandline.Main.run(Main.java:79)
	at com.buschmais.jqassistant.commandline.Main.main(Main.java:50)`

Tested on
 - macOS, Java 11, jQAssistant 1.7, plugin v0.0.4
 - macOS, Java 11,  jQAssistant 1.6, plugin v0.3
 - Linux, Java 13, jQAssistant 1.7, plugin v0.0.4
 - Linux, Java 13, jQAssistant 1.6, plugin v0.3

**Comment by naraesk** [comment]
Same here with jQassistant 1.7 and plugin version v0.0.4.
Tested on Linux with java 8

**Comment by b-pos465** [comment]
I just upgraded the plugin to **jQAssistant 1.8** which fixes the issue above.

Now there is another issue:

`run/jqassistant-commandline-neo4jv3-1.8.0/bin/jqassistant.sh scan -f run/githubissues.xml` works perfectly fine.

However, `run/jqassistant-commandline-neo4jv3-1.8.0/bin/jqassistant.sh server` fails with the following error:

```bash
Exception in thread "main" org.neo4j.server.ServerStartupException: Starting Neo4j failed: Component 'org.neo4j.server.AbstractNeoServer$ServerComponentsLifecycleAdapter@44e79e9e' was successfully initialized, but failed to start. Please see the attached cause exception "ClassCastEx
ception: attempting to castjar:file:/P:/Repositories/jqa-githubissues-plugin/run/jqassistant-commandline-neo4jv3-1.8.0/plugins/jqa-githubissues-plugin-0.0.4.jar!/javax/ws/rs/ext/RuntimeDelegate.classtojar:file:/P:/Repositories/jqa-githubissues-plugin/run/jqassistant-commandline-neo4
jv3-1.8.0/lib/org.neo4j.3rdparty.javax.ws.rs-jsr311-api-1.1.2.r612.jar!/javax/ws/rs/ext/RuntimeDelegate.class".
        at org.neo4j.server.exception.ServerStartupErrors.translateToServerStartupError(ServerStartupErrors.java:45)
        at org.neo4j.server.AbstractNeoServer.start(AbstractNeoServer.java:187)
        at com.buschmais.jqassistant.neo4j.backend.neo4jv3.Neo4jV3CommunityNeoServer.start(Neo4jV3CommunityNeoServer.java:63)
        at com.buschmais.jqassistant.commandline.task.ServerTask.executeTask(ServerTask.java:37)
        at com.buschmais.jqassistant.commandline.task.AbstractStoreTask.run(AbstractStoreTask.java:47)
        at com.buschmais.jqassistant.commandline.Main.executeTask(Main.java:254)
        at com.buschmais.jqassistant.commandline.Main.executeTasks(Main.java:203)
        at com.buschmais.jqassistant.commandline.Main.interpretCommandLine(Main.java:195)
        at com.buschmais.jqassistant.commandline.Main.run(Main.java:78)
        at com.buschmais.jqassistant.commandline.Main.main(Main.java:49)
Caused by: org.neo4j.kernel.lifecycle.LifecycleException: Component 'org.neo4j.server.AbstractNeoServer$ServerComponentsLifecycleAdapter@44e79e9e' was successfully initialized, but failed to start. Please see the attached cause exception "ClassCastException: attempting to castjar:fi
le:/P:/Repositories/jqa-githubissues-plugin/run/jqassistant-commandline-neo4jv3-1.8.0/plugins/jqa-githubissues-plugin-0.0.4.jar!/javax/ws/rs/ext/RuntimeDelegate.classtojar:file:/P:/Repositories/jqa-githubissues-plugin/run/jqassistant-commandline-neo4jv3-1.8.0/lib/org.neo4j.3rdparty.
javax.ws.rs-jsr311-api-1.1.2.r612.jar!/javax/ws/rs/ext/RuntimeDelegate.class".
        at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:473)
        at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:111)
        at org.neo4j.server.AbstractNeoServer.start(AbstractNeoServer.java:180)
        ... 8 more
Caused by: java.lang.LinkageError: ClassCastException: attempting to castjar:file:/P:/Repositories/jqa-githubissues-plugin/run/jqassistant-commandline-neo4jv3-1.8.0/plugins/jqa-githubissues-plugin-0.0.4.jar!/javax/ws/rs/ext/RuntimeDelegate.classtojar:file:/P:/Repositories/jqa-github
issues-plugin/run/jqassistant-commandline-neo4jv3-1.8.0/lib/org.neo4j.3rdparty.javax.ws.rs-jsr311-api-1.1.2.r612.jar!/javax/ws/rs/ext/RuntimeDelegate.class
        at javax.ws.rs.ext.RuntimeDelegate.findDelegate(RuntimeDelegate.java:144)
        at javax.ws.rs.ext.RuntimeDelegate.getInstance(RuntimeDelegate.java:119)
        at javax.ws.rs.core.EntityTag.<clinit>(EntityTag.java:63)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Unknown Source)
        at com.sun.proxy.$Proxy113.<clinit>(Unknown Source)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
        at java.lang.reflect.Constructor.newInstance(Unknown Source)
        at java.lang.reflect.Proxy.newProxyInstance(Unknown Source)
        at com.sun.jersey.server.impl.application.WebApplicationImpl$26.run(WebApplicationImpl.java:1626)
        at java.security.AccessController.doPrivileged(Native Method)
        at com.sun.jersey.server.impl.application.WebApplicationImpl.createProxy(WebApplicationImpl.java:1623)
        at com.sun.jersey.server.impl.application.WebApplicationImpl.<init>(WebApplicationImpl.java:335)
        at com.sun.jersey.server.impl.container.WebApplicationProviderImpl.createWebApplication(WebApplicationProviderImpl.java:55)
        at com.sun.jersey.spi.container.WebApplicationFactory.createWebApplication(WebApplicationFactory.java:66)
        at com.sun.jersey.spi.container.servlet.ServletContainer.create(ServletContainer.java:412)
        at com.sun.jersey.spi.container.servlet.ServletContainer$InternalWebComponent.create(ServletContainer.java:327)
        at com.sun.jersey.spi.container.servlet.WebComponent.load(WebComponent.java:603)
        at com.sun.jersey.spi.container.servlet.WebComponent.init(WebComponent.java:207)
        at com.sun.jersey.spi.container.servlet.ServletContainer.init(ServletContainer.java:394)
        at com.sun.jersey.spi.container.servlet.ServletContainer.init(ServletContainer.java:577)
        at javax.servlet.GenericServlet.init(GenericServlet.java:244)
        at org.eclipse.jetty.servlet.ServletHolder.initServlet(ServletHolder.java:671)
        at org.eclipse.jetty.servlet.ServletHolder.initialize(ServletHolder.java:428)
        at org.eclipse.jetty.servlet.ServletHandler.lambda$initialize$0(ServletHandler.java:750)
        at java.util.stream.SortedOps$SizedRefSortingSink.end(Unknown Source)
        at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
        at java.util.stream.StreamSpliterators$WrappingSpliterator.forEachRemaining(Unknown Source)
        at java.util.stream.Streams$ConcatSpliterator.forEachRemaining(Unknown Source)
        at java.util.stream.Streams$ConcatSpliterator.forEachRemaining(Unknown Source)
        at java.util.stream.ReferencePipeline$Head.forEach(Unknown Source)
        at org.eclipse.jetty.servlet.ServletHandler.initialize(ServletHandler.java:744)
        at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:369)
        at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:852)
        at org.eclipse.jetty.servlet.ServletContextHandler.doStart(ServletContextHandler.java:278)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:167)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:119)
        at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:113)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:167)
        at org.eclipse.jetty.server.Server.start(Server.java:418)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:110)
        at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:113)
        at org.eclipse.jetty.server.Server.doStart(Server.java:382)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
        at org.neo4j.server.web.Jetty9WebServer.startJetty(Jetty9WebServer.java:329)
        at org.neo4j.server.web.Jetty9WebServer.start(Jetty9WebServer.java:159)
        at org.neo4j.server.AbstractNeoServer.startWebServer(AbstractNeoServer.java:290)
        at org.neo4j.server.AbstractNeoServer$ServerComponentsLifecycleAdapter.start(AbstractNeoServer.java:543)
        at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:452)
        ... 10 more
```

This **does not** occur when I delete the plugin from the `plugins` folder. Unfortunately, the error message is not really helpful.

@DirkMahler, can you provide some hints here?

**Comment by DirkMahler** [comment]
I've upgraded the plugin to jQA 1.8, see https://github.com/softvis-research/jqa-githubissues-plugin/pull/7. 

- Used the generated plugin with the CLI (1.8.0) for successfully scanning a GitHub project
- ScannerIT is broken but this IMHO not related to jQA version, needs to be fixed

**Comment by b-pos465** [comment]
Thank you! I just merged the changes. I will have a look at the `ScannerIT`.

**Comment by b-pos465** [comment]
@DirkMahler: Unfortunately, the error above still occurs. It is not the scanning step that fails but the Neo4J server start triggered with
```
run/jqassistant-commandline-neo4jv3-1.8.0/bin/jqassistant.sh server
```

**Comment by b-pos465** [comment]
I just merged the pull request and it works like a charm :)

Thank you for your time, @DirkMahler!
